export const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
] as const;

export type LanguageCode = typeof LANGUAGES[number]["code"];

export const UI_STRINGS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appName: "Sanjeevani",
    tagline: "Integrative care, in your language",
    modulesNav: "Modules",
    howItWorksNav: "How it works",
    safetyNav: "Safety",
    patientPortalNav: "Patient Portal",
    forCliniciansNav: "For Clinicians",
    chooseLanguage: "Choose language",
    startIntake: "Start patient intake",
    yourLanguage: "Your language",
    symptoms: "What are you experiencing?",
    symptomsPlaceholder: "Describe your symptoms in your own words…",
    duration: "How long?",
    age: "Age",
    sex: "Sex",
    comorbidities: "Existing conditions (diabetes, hypertension…)",
    medications: "Current medications",
    allergies: "Known allergies",
    preferences: "Treatment preferences",
    next: "Next",
    back: "Back",
    analyze: "Get integrative plan",
    analyzing: "Analyzing across modalities…",
  },
  hi: {
    appName: "संजीवनी",
    tagline: "आपकी भाषा में, समग्र चिकित्सा",
    modulesNav: "मॉड्यूल",
    howItWorksNav: "यह कैसे काम करता है",
    safetyNav: "सुरक्षा",
    patientPortalNav: "रोगी पोर्टल",
    forCliniciansNav: "चिकित्सकों के लिए",
    chooseLanguage: "भाषा चुनें",
    startIntake: "रोगी जानकारी शुरू करें",
    yourLanguage: "आपकी भाषा",
    symptoms: "आप क्या अनुभव कर रहे हैं?",
    symptomsPlaceholder: "अपने शब्दों में लक्षण बताइए…",
    duration: "कितने समय से?",
    age: "उम्र",
    sex: "लिंग",
    comorbidities: "मौजूदा बीमारियाँ (मधुमेह, उच्च रक्तचाप…)",
    medications: "वर्तमान दवाइयाँ",
    allergies: "ज्ञात एलर्जी",
    preferences: "उपचार पसंद",
    next: "आगे",
    back: "पीछे",
    analyze: "समग्र योजना प्राप्त करें",
    analyzing: "सभी पद्धतियों में विश्लेषण…",
  },
  ta: {
    appName: "சஞ்சீவனி",
    tagline: "உங்கள் மொழியில் ஒருங்கிணைந்த சிகிச்சை",
    modulesNav: "தொகுதிகள்",
    howItWorksNav: "இது எப்படி செயல்படுகிறது",
    safetyNav: "பாதுகாப்பு",
    patientPortalNav: "நோயாளர் தளம்",
    forCliniciansNav: "மருத்துவர்களுக்காக",
    chooseLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    startIntake: "நோயாளர் தகவலை தொடங்கவும்",
    yourLanguage: "உங்கள் மொழி",
    symptoms: "நீங்கள் என்ன அனுபவிக்கிறீர்கள்?",
    symptomsPlaceholder: "உங்கள் சொற்களில் அறிகுறிகளை விவரிக்கவும்…",
    duration: "எத்தனை நாட்களாக?",
    age: "வயது",
    sex: "பாலினம்",
    comorbidities: "ஏற்கனவே உள்ள நிலைகள்",
    medications: "தற்போதைய மருந்துகள்",
    allergies: "அறியப்பட்ட ஒவ்வாமைகள்",
    preferences: "சிகிச்சை விருப்பங்கள்",
    next: "அடுத்து",
    back: "பின்",
    analyze: "ஒருங்கிணைந்த திட்டத்தை பெறுங்கள்",
    analyzing: "அனைத்து முறைகளிலும் பகுப்பாய்வு…",
  },
  te: {
    appName: "సంజీవని",
    tagline: "మీ భాషలో, సమగ్ర వైద్యం",
    modulesNav: "మాడ్యూల్స్",
    howItWorksNav: "ఇది ఎలా పనిచేస్తుంది",
    safetyNav: "భద్రత",
    patientPortalNav: "రోగి పోర్టల్",
    forCliniciansNav: "వైద్యుల కోసం",
    chooseLanguage: "భాషను ఎంచుకోండి",
    startIntake: "రోగి సమాచారం ప్రారంభించండి",
    yourLanguage: "మీ భాష",
    symptoms: "మీరు ఏమి అనుభవిస్తున్నారు?",
    symptomsPlaceholder: "మీ మాటల్లో లక్షణాలను వివరించండి…",
    duration: "ఎంతకాలం నుండి?",
    age: "వయస్సు",
    sex: "లింగం",
    comorbidities: "ఇప్పటికే ఉన్న పరిస్థితులు (మధుమేహం, రక్తపోటు…)",
    medications: "ప్రస్తుత మందులు",
    allergies: "తెలిసిన అలెర్జీలు",
    preferences: "చికిత్స ప్రాధాన్యతలు",
    next: "తర్వాత",
    back: "వెనుకకు",
    analyze: "సమగ్ర ప్రణాళిక పొందండి",
    analyzing: "అన్ని పద్ధతులలో విశ్లేషణ…",
  },
  bn: {
    appName: "সঞ্জীবনী",
    tagline: "আপনার ভাষায় সমন্বিত চিকিৎসা",
    modulesNav: "মডিউলসমূহ",
    howItWorksNav: "এটি কীভাবে কাজ করে",
    safetyNav: "নিরাপত্তা",
    patientPortalNav: "রোগী পোর্টাল",
    forCliniciansNav: "চিকিৎসকদের জন্য",
    chooseLanguage: "ভাষা নির্বাচন করুন",
    startIntake: "রোগীর তথ্য শুরু করুন",
    yourLanguage: "আপনার ভাষা",
    symptoms: "আপনি কী অনুভব করছেন?",
    symptomsPlaceholder: "নিজের ভাষায় উপসর্গ লিখুন…",
    duration: "কতদিন ধরে?",
    age: "বয়স",
    sex: "লিঙ্গ",
    comorbidities: "আগের রোগসমূহ",
    medications: "বর্তমান ওষুধ",
    allergies: "পরিচিত অ্যালার্জি",
    preferences: "চিকিৎসার পছন্দ",
    next: "পরবর্তী",
    back: "পিছনে",
    analyze: "সমন্বিত পরিকল্পনা পান",
    analyzing: "সব পদ্ধতিতে বিশ্লেষণ…",
  },
  mr: {
    appName: "संजीवनी",
    tagline: "तुमच्या भाषेत समन्वित आरोग्यसेवा",
    modulesNav: "मॉड्यूल्स",
    howItWorksNav: "हे कसे काम करते",
    safetyNav: "सुरक्षा",
    patientPortalNav: "रुग्ण पोर्टल",
    forCliniciansNav: "चिकित्सकांसाठी",
    chooseLanguage: "भाषा निवडा",
    startIntake: "रुग्ण माहिती सुरू करा",
    yourLanguage: "तुमची भाषा",
    symptoms: "तुम्हाला काय त्रास होत आहे?",
    symptomsPlaceholder: "तुमच्या शब्दांत लक्षणे लिहा…",
    duration: "किती दिवसांपासून?",
    age: "वय",
    sex: "लिंग",
    comorbidities: "आधीपासून असलेल्या तक्रारी",
    medications: "सध्याची औषधे",
    allergies: "माहित असलेल्या अॅलर्जी",
    preferences: "उपचाराची पसंती",
    next: "पुढे",
    back: "मागे",
    analyze: "समन्वित योजना मिळवा",
    analyzing: "सर्व पद्धतींमध्ये विश्लेषण…",
  },
  kn: {
    appName: "ಸಂಜೀವಿನಿ",
    tagline: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ, ಸಮಗ್ರ ಆರೈಕೆ",
    modulesNav: "ಮಾಡ್ಯೂಲ್‌ಗಳು",
    howItWorksNav: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    safetyNav: "ಸುರಕ್ಷತೆ",
    patientPortalNav: "ರೋಗಿ ಪೋರ್ಟಲ್",
    forCliniciansNav: "ವೈದ್ಯರಿಗಾಗಿ",
    chooseLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    startIntake: "ರೋಗಿಯ ಮಾಹಿತಿ ಪ್ರಾರಂಭಿಸಿ",
    yourLanguage: "ನಿಮ್ಮ ಭಾಷೆ",
    symptoms: "ನೀವು ಏನು ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ?",
    symptomsPlaceholder: "ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ…",
    duration: "ಎಷ್ಟು ಸಮಯದಿಂದ?",
    age: "ವಯಸ್ಸು",
    sex: "ಲಿಂಗ",
    comorbidities: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಸ್ಥಿತಿಗಳು (ಮಧುಮೇಹ, ಅಧಿಕ ರಕ್ತದೊತ್ತಡ…)",
    medications: "ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು",
    allergies: "ತಿಳಿದಿರುವ ಅಲರ್ಜಿಗಳು",
    preferences: "ಚಿಕಿತ್ಸೆಯ ಆದ್ಯತೆಗಳು",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    analyze: "ಸಮಗ್ರ ಯೋಜನೆ ಪಡೆಯಿರಿ",
    analyzing: "ಎಲ್ಲಾ ಪದ್ಧತಿಗಳಲ್ಲಿ ವಿಶ್ಲೇಷಣೆ…",
  },
  ml: {
    appName: "സഞ്ജീവനി",
    tagline: "നിങ്ങളുടെ ഭാഷയിൽ, സമഗ്ര പരിചരണം",
    modulesNav: "മോഡ്യൂളുകൾ",
    howItWorksNav: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    safetyNav: "സുരക്ഷ",
    patientPortalNav: "രോഗി പോർട്ടൽ",
    forCliniciansNav: "ഡോക്ടർമാർക്കായി",
    chooseLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    startIntake: "രോഗി വിവരങ്ങൾ ആരംഭിക്കുക",
    yourLanguage: "നിങ്ങളുടെ ഭാഷ",
    symptoms: "നിങ്ങൾ എന്താണ് അനുഭവിക്കുന്നത്?",
    symptomsPlaceholder: "നിങ്ങളുടെ വാക്കുകളിൽ ലക്ഷണങ്ങൾ വിവരിക്കുക…",
    duration: "എത്ര നാളായി?",
    age: "പ്രായം",
    sex: "ലിംഗം",
    comorbidities: "നിലവിലുള്ള അവസ്ഥകൾ (പ്രമേഹം, രക്തസമ്മർദ്ദം…)",
    medications: "നിലവിലെ മരുന്നുകൾ",
    allergies: "അറിയപ്പെടുന്ന അലർജികൾ",
    preferences: "ചികിത്സാ മുൻഗണനകൾ",
    next: "അടുത്തത്",
    back: "പുറകോട്ട്",
    analyze: "സമഗ്ര പദ്ധതി നേടുക",
    analyzing: "എല്ലാ രീതികളിലും വിശകലനം…",
  },
};

export const t = (lang: LanguageCode, key: string) =>
  UI_STRINGS[lang]?.[key] ?? UI_STRINGS.en[key] ?? key;

export const getLanguageName = (code: string) =>
  LANGUAGES.find((language) => language.code === code)?.name ?? "English";

export const getLanguageNative = (code: string) =>
  LANGUAGES.find((language) => language.code === code)?.native ?? "English";
